# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2026-06-19 20:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('variables', django.contrib.postgres.fields.jsonb.JSONField()),
                ('variables_compatibles', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='collections.Collection')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
    ]
