# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2026-06-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0022_auto_20260623_0943'),
        ('management', '0003_distributionvalidatorconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCollectionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Procesando catálogos'), ('FINISHED', 'Finalizada')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('logs', models.TextField()),
                ('indexing_mode', models.CharField(choices=[('updated', 'Sólo actualizados'), ('all', 'Todos (forzar indexación)')], default='updated', max_length=200)),
                ('node', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node')),
            ],
            options={
                'verbose_name': 'Indexación de colección',
                'verbose_name_plural': 'Corridas de indexación de colecciones',
            },
        ),
        migrations.AlterModelOptions(
            name='distributionvalidatorconfig',
            options={'verbose_name': 'Configuración de validaciones para indexación'},
        ),
    ]
